/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Utility.Util;
import java.awt.Color;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import model.Advokat;
import model.AnalisisHukum;
import model.Klient;
import model.Konsultasi;
import service.advokatService;
import service.analisisService;
import service.impl.advokatServiceImpl;
import service.impl.analisisServiceImpl;
import service.impl.klientServiceImpl;
import service.impl.konsultasiServiceImpl;
import service.klientService;
import service.konsultasiService;


/**
 *
 * @author solosz
 */
public class FrameApp extends javax.swing.JFrame {
    
    private advokatService serviceadvokat =  new advokatServiceImpl();
    private klientService serviceklient = new klientServiceImpl();
    private analisisService serviceanalisis = new analisisServiceImpl();
    private konsultasiService servicekonsultasi = new konsultasiServiceImpl();

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.DARK_GRAY);
        dateKonsultasi.setDate(new java.util.Date());
        dateAnalisis.setDate(new java.util.Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnKlient = new javax.swing.JButton();
        btnAdvokat = new javax.swing.JButton();
        btnKonsultasi = new javax.swing.JButton();
        btnAnalisis = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlKlient = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdKlient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNamaKlient = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmailKlient = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelpKlient = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIdentitasKlient = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pwKlient = new javax.swing.JPasswordField();
        btnInputKlient = new javax.swing.JButton();
        btnCariKlient = new javax.swing.JButton();
        txtCariKlient = new javax.swing.JTextField();
        pnlAdvokat = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdAdvokat = new javax.swing.JTextField();
        txtNamaAdvokat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEmailAdvokat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTelpAdvokat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtIdentitasAdvokat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnInputAdvokat = new javax.swing.JButton();
        pwAdvokat = new javax.swing.JPasswordField();
        btnCariAdvokat = new javax.swing.JButton();
        txtCariAdvokat = new javax.swing.JTextField();
        pnlKonsultasi = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtIdKonsultasi = new javax.swing.JTextField();
        txtIdKlientKonsultasi = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaPertanyaanKonsultasi = new javax.swing.JTextArea();
        dateKonsultasi = new com.toedter.calendar.JDateChooser();
        cmbStatusKonsultasi = new javax.swing.JComboBox<>();
        btnInputKonsultasi = new javax.swing.JButton();
        btnCariKonsultasi = new javax.swing.JButton();
        txtCariKonsultasi = new javax.swing.JTextField();
        pnlAnalisis = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtIdAnalisis = new javax.swing.JTextField();
        txtIdKonsultasiAnalisis = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtIdAdvokatAnalisis = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaAnalisis = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaRekomedasiAnalisis = new javax.swing.JTextArea();
        dateAnalisis = new com.toedter.calendar.JDateChooser();
        btnInputAnalisis = new javax.swing.JButton();
        btnCariAnalisis = new javax.swing.JButton();
        txtCariAnalisis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Legal Balance");
        setBackground(java.awt.Color.darkGray);
        setName("frameApp"); // NOI18N
        setSize(new java.awt.Dimension(0, 0));

        Menu.setBackground(new java.awt.Color(153, 153, 153));

        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnKlient.setText("KLIENT");
        btnKlient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlientActionPerformed(evt);
            }
        });

        btnAdvokat.setText("ADVOKAT");
        btnAdvokat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvokatActionPerformed(evt);
            }
        });

        btnKonsultasi.setText("KONSULTASI");
        btnKonsultasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonsultasiActionPerformed(evt);
            }
        });

        btnAnalisis.setText("ANALISIS HUKUM");
        btnAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnKlient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btnAdvokat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btnKonsultasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btnAnalisis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKlient, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        Header.setBackground(new java.awt.Color(33, 37, 41));

        LOGO.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        LOGO.setForeground(new java.awt.Color(255, 255, 255));
        LOGO.setText("LEGAL BALANCE");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(LOGO)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LOGO)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Content.setBackground(new java.awt.Color(204, 204, 204));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("<html>\n  <h1 style=\"color:#212529; font-size:18pt; text-align:center;\">\n    Legal Balance – Solusi Hukum Anda, <span style=\"color:#212529;\">Tepat</span> dan <span style=\"color:#212529;\">Terjangkau</span>!\n  </h1>\n  <p style=\"text-align:center; font-size:12pt; margin-top:10px;\">\n    Dapatkan konsultasi hukum cepat dari para ahli di bidangnya.<br>\n    Legal Balance hadir untuk memudahkan Anda mengatasi masalah hukum dengan lebih percaya diri.\n  </p>\n</html>");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("<html>\n  <h2 style=\"color:#2c3e50; font-size:16pt; text-align:justify;\">Apa Itu Legal Balance?</h2>\n  <p style=\"text-align:center; font-size:12pt; margin:5px;\">\n    <span style=\"font-weight:bold;\">Platform konsultasi hukum online</span> yang menghubungkan Anda dengan<br>\n    advokat, notaris, dan ahli hukum berpengalaman. Dengan fitur:<br>\n    <span style=\"color:#27ae60;\">✓ Chat langsung</span> | \n    <span style=\"color:#27ae60;\">✓ Booking konsultasi</span> | \n    <span style=\"color:#27ae60;\">✓ Artikel hukum terpercaya</span>\n  </p>\n</html>");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("<html>\n  <h2 style=\"color:#2c3e50; font-size:16pt; text-align:justify;\">Mengapa Pilih Legal Balance?</h2>\n  <ul style=\"font-size:12pt; margin-left:20px; padding-left:10px;\">\n    <li><span style=\"color:#2980b9;\">✓ Konsultasi Praktis</span>: Tanya jawab via chat/video call</li>\n    <li><span style=\"color:#2980b9;\">✓ Ahli Terverifikasi</span>: Tim hukum profesional</li>\n    <li><span style=\"color:#2980b9;\">✓ Transparan</span>: Biaya jelas, no hidden cost</li>\n    <li><span style=\"color:#2980b9;\">✓ Informasi Terkini</span>: Artikel hukum terupdate</li>\n  </ul>\n</html>");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("<html>   <p style=\"text-align:center; font-size:18pt; font-weight:bold; color:#2c3e50;\">     Butuh Bantuan Hukum?   </p>   <p style=\"text-align:center; font-size:14pt;\">     Jangan biarkan masalah hukum mengganggu hidup Anda.<br>     <span style=\"background-color:#3498db; color:white; padding:3px 8px; border-radius:3px;\">       Konsultasi Sekarang     </span>   </p> </html>");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        Content.add(pnlHome, "card2");

        pnlKlient.setBackground(new java.awt.Color(255, 255, 255));
        pnlKlient.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        jLabel5.setText("KLIENT");

        jLabel6.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel6.setLabelFor(txtIdKlient);
        jLabel6.setText("ID");

        txtIdKlient.setBackground(new java.awt.Color(239, 239, 239));
        txtIdKlient.setPreferredSize(new java.awt.Dimension(300, 30));
        txtIdKlient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdKlientActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel7.setText("Nama");

        txtNamaKlient.setBackground(new java.awt.Color(239, 239, 239));
        txtNamaKlient.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel8.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel8.setText("Email");

        txtEmailKlient.setBackground(new java.awt.Color(239, 239, 239));
        txtEmailKlient.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel9.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel9.setText("Password");

        txtTelpKlient.setBackground(new java.awt.Color(239, 239, 239));
        txtTelpKlient.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel10.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel10.setText("No Telp");

        txtIdentitasKlient.setBackground(new java.awt.Color(239, 239, 239));
        txtIdentitasKlient.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel11.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel11.setText("No Identitas");

        pwKlient.setBackground(new java.awt.Color(239, 239, 239));
        pwKlient.setPreferredSize(new java.awt.Dimension(300, 30));

        btnInputKlient.setText("Tambah");
        btnInputKlient.setPreferredSize(new java.awt.Dimension(100, 40));
        btnInputKlient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputKlientActionPerformed(evt);
            }
        });

        btnCariKlient.setText("Cari Data");
        btnCariKlient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKlientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKlientLayout = new javax.swing.GroupLayout(pnlKlient);
        pnlKlient.setLayout(pnlKlientLayout);
        pnlKlientLayout.setHorizontalGroup(
            pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKlientLayout.createSequentialGroup()
                .addGroup(pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlKlientLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInputKlient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKlientLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(btnCariKlient, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(197, 197, 197)
                        .addGroup(pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwKlient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelpKlient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdentitasKlient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmailKlient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNamaKlient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdKlient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCariKlient))))
                .addGap(88, 88, 88))
            .addGroup(pnlKlientLayout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKlientLayout.setVerticalGroup(
            pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKlientLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdKlient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNamaKlient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmailKlient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pwKlient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTelpKlient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIdentitasKlient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnInputKlient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(pnlKlientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCariKlient, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCariKlient, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        Content.add(pnlKlient, "card6");

        pnlAdvokat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        jLabel12.setText("ADVOKAT");

        jLabel13.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel13.setText("ID");

        txtIdAdvokat.setBackground(new java.awt.Color(239, 239, 239));
        txtIdAdvokat.setPreferredSize(new java.awt.Dimension(300, 30));

        txtNamaAdvokat.setBackground(new java.awt.Color(239, 239, 239));
        txtNamaAdvokat.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel14.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel14.setText("Nama");

        txtEmailAdvokat.setBackground(new java.awt.Color(239, 239, 239));
        txtEmailAdvokat.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel15.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel15.setText("Email");

        jLabel16.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel16.setText("Password");

        txtTelpAdvokat.setBackground(new java.awt.Color(239, 239, 239));
        txtTelpAdvokat.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel17.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel17.setText("No Telp");

        txtIdentitasAdvokat.setBackground(new java.awt.Color(239, 239, 239));
        txtIdentitasAdvokat.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel18.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel18.setText("No Identitas");

        btnInputAdvokat.setText("Tambah");
        btnInputAdvokat.setPreferredSize(new java.awt.Dimension(100, 40));
        btnInputAdvokat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputAdvokatActionPerformed(evt);
            }
        });

        pwAdvokat.setBackground(new java.awt.Color(239, 239, 239));
        pwAdvokat.setPreferredSize(new java.awt.Dimension(300, 30));

        btnCariAdvokat.setText("Cari Data");
        btnCariAdvokat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariAdvokatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdvokatLayout = new javax.swing.GroupLayout(pnlAdvokat);
        pnlAdvokat.setLayout(pnlAdvokatLayout);
        pnlAdvokatLayout.setHorizontalGroup(
            pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdvokatLayout.createSequentialGroup()
                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAdvokatLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInputAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAdvokatLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdvokatLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAdvokatLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNamaAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAdvokatLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmailAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdvokatLayout.createSequentialGroup()
                                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pwAdvokat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTelpAdvokat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdvokatLayout.createSequentialGroup()
                                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(btnCariAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdentitasAdvokat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCariAdvokat))))))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdvokatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(385, 385, 385))
        );
        pnlAdvokatLayout.setVerticalGroup(
            pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdvokatLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addGap(37, 37, 37)
                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtIdAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNamaAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEmailAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pwAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTelpAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtIdentitasAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnInputAdvokat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlAdvokatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCariAdvokat, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnCariAdvokat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        Content.add(pnlAdvokat, "card5");

        pnlKonsultasi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        jLabel19.setText("KONSULTASI");

        jLabel20.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel20.setText("ID");

        txtIdKonsultasi.setPreferredSize(new java.awt.Dimension(300, 30));

        txtIdKlientKonsultasi.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel21.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel21.setText("ID Klient");

        jLabel22.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel22.setText("Pertanyaan");

        jLabel23.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel23.setText("Tanggal");

        jLabel24.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel24.setText("Status");

        areaPertanyaanKonsultasi.setColumns(20);
        areaPertanyaanKonsultasi.setRows(5);
        areaPertanyaanKonsultasi.setPreferredSize(new java.awt.Dimension(300, 30));
        jScrollPane1.setViewportView(areaPertanyaanKonsultasi);

        dateKonsultasi.setPreferredSize(new java.awt.Dimension(300, 30));

        cmbStatusKonsultasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MENUNGGU", "PROSES", "SELESAI" }));
        cmbStatusKonsultasi.setPreferredSize(new java.awt.Dimension(76, 30));

        btnInputKonsultasi.setText("Tambah");
        btnInputKonsultasi.setPreferredSize(new java.awt.Dimension(100, 40));
        btnInputKonsultasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputKonsultasiActionPerformed(evt);
            }
        });

        btnCariKonsultasi.setText("Cari Data");
        btnCariKonsultasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKonsultasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKonsultasiLayout = new javax.swing.GroupLayout(pnlKonsultasi);
        pnlKonsultasi.setLayout(pnlKonsultasiLayout);
        pnlKonsultasiLayout.setHorizontalGroup(
            pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKonsultasiLayout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlKonsultasiLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKonsultasiLayout.createSequentialGroup()
                        .addComponent(btnCariKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlKonsultasiLayout.createSequentialGroup()
                        .addGroup(pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlKonsultasiLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnInputKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlKonsultasiLayout.createSequentialGroup()
                                .addGroup(pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                                .addGroup(pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbStatusKonsultasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateKonsultasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlKonsultasiLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane1)
                                                .addComponent(txtIdKlientKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtCariKonsultasi))))
                        .addGap(76, 76, 76))))
        );
        pnlKonsultasiLayout.setVerticalGroup(
            pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKonsultasiLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel19)
                .addGap(38, 38, 38)
                .addGroup(pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlKonsultasiLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23))
                    .addGroup(pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlKonsultasiLayout.createSequentialGroup()
                            .addComponent(txtIdKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtIdKlientKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44))
                        .addComponent(dateKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatusKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(47, 47, 47)
                .addComponent(btnInputKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(pnlKonsultasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCariKonsultasi, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(txtCariKonsultasi))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        Content.add(pnlKonsultasi, "card4");

        pnlAnalisis.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        jLabel25.setText("ANALISIS HUKUM");

        jLabel26.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel26.setText("ID");

        txtIdAnalisis.setPreferredSize(new java.awt.Dimension(300, 30));

        txtIdKonsultasiAnalisis.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel27.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel27.setText("ID Konsultasi");

        jLabel28.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel28.setText("ID Advokat");

        txtIdAdvokatAnalisis.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel29.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel29.setText("Analisis");

        jLabel30.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel30.setText("Rekomendasi");

        jLabel31.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel31.setText("Tanggal");

        areaAnalisis.setColumns(20);
        areaAnalisis.setRows(5);
        areaAnalisis.setPreferredSize(new java.awt.Dimension(300, 30));
        jScrollPane2.setViewportView(areaAnalisis);

        areaRekomedasiAnalisis.setColumns(20);
        areaRekomedasiAnalisis.setRows(5);
        areaRekomedasiAnalisis.setPreferredSize(new java.awt.Dimension(300, 30));
        jScrollPane3.setViewportView(areaRekomedasiAnalisis);

        dateAnalisis.setPreferredSize(new java.awt.Dimension(300, 30));

        btnInputAnalisis.setText("Tambah");
        btnInputAnalisis.setPreferredSize(new java.awt.Dimension(100, 40));
        btnInputAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputAnalisisActionPerformed(evt);
            }
        });

        btnCariAnalisis.setText("Cari Data");
        btnCariAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariAnalisisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAnalisisLayout = new javax.swing.GroupLayout(pnlAnalisis);
        pnlAnalisis.setLayout(pnlAnalisisLayout);
        pnlAnalisisLayout.setHorizontalGroup(
            pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAnalisisLayout.createSequentialGroup()
                .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAnalisisLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInputAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAnalisisLayout.createSequentialGroup()
                        .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAnalisisLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel28)))
                            .addGroup(pnlAnalisisLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btnCariAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdKonsultasiAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(dateAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(txtIdAdvokatAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCariAnalisis))))
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAnalisisLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(310, 310, 310))
        );
        pnlAnalisisLayout.setVerticalGroup(
            pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnalisisLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel25)
                .addGap(28, 28, 28)
                .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAnalisisLayout.createSequentialGroup()
                        .addComponent(txtIdAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdKonsultasiAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdAdvokatAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(32, 32, 32)
                .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(33, 33, 33)
                .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(dateAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnInputAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCariAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(txtCariAnalisis))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Content.add(pnlAnalisis, "card3");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll();
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnKlientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlientActionPerformed
        Content.removeAll();
        Content.add(pnlKlient);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnKlientActionPerformed

    private void btnAdvokatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvokatActionPerformed
        Content.removeAll();
        Content.add(pnlAdvokat);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnAdvokatActionPerformed

    private void btnKonsultasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonsultasiActionPerformed
        Content.removeAll();
        Content.add(pnlKonsultasi);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnKonsultasiActionPerformed

    private void btnAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisisActionPerformed
        Content.removeAll();
        Content.add(pnlAnalisis);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnAnalisisActionPerformed

    private void txtIdKlientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKlientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKlientActionPerformed

    private void btnInputAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputAnalisisActionPerformed
        AnalisisHukum analisisHukum =  new AnalisisHukum();
        analisisHukum.setId_analisis(txtIdAnalisis.getText());
        analisisHukum.setId_advokat(txtIdAdvokatAnalisis.getText());
        analisisHukum.setId_konsultasi(txtIdKonsultasiAnalisis.getText());
        analisisHukum.setAnalisis(areaAnalisis.getText());
        analisisHukum.setRekomendasi(areaRekomedasiAnalisis.getText());
        analisisHukum.setTanggal(dateAnalisis.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        
        
        this.serviceanalisis.tambahAnalisisHukum(analisisHukum);
        Util.resetForm(txtIdAnalisis, txtIdAdvokatAnalisis, txtIdKonsultasiAnalisis);
        Util.resetForm(areaAnalisis, areaRekomedasiAnalisis);
        
    }//GEN-LAST:event_btnInputAnalisisActionPerformed

    private void btnInputKlientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputKlientActionPerformed
        Klient klient = new Klient();
        klient.setId_klien(txtIdKlient.getText());
        klient.setNama(txtNamaKlient.getText());
        klient.setEmail(txtEmailKlient.getText());
        
        klient.setPassword(new String(pwKlient.getPassword()));
        
        klient.setTelp(txtTelpKlient.getText());
        klient.setIdentitas(txtIdentitasKlient.getText());
        
        
        serviceklient.tambahKlient(klient);
        Util.resetForm(txtIdKlient, txtNamaKlient, txtEmailKlient, pwKlient, txtTelpKlient, txtIdentitasKlient);
        
        
    }//GEN-LAST:event_btnInputKlientActionPerformed

    private void btnInputAdvokatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputAdvokatActionPerformed
        Advokat advokat = new Advokat();
        advokat.setId_advokat(txtIdAdvokat.getText());
        advokat.setNama(txtNamaAdvokat.getText());
        advokat.setEmail(txtEmailAdvokat.getText());
        advokat.setPassword(new String(pwAdvokat.getPassword()));
        advokat.setTelp(txtTelpAdvokat.getText());
        advokat.setIdentitas(txtIdentitasAdvokat.getText());

        serviceadvokat.tambahAdvokat(advokat);
        Util.resetForm(txtIdAdvokat, txtNamaAdvokat, txtEmailAdvokat, pwAdvokat, txtTelpAdvokat, txtIdentitasAdvokat);

    }//GEN-LAST:event_btnInputAdvokatActionPerformed

    private void btnInputKonsultasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputKonsultasiActionPerformed
        Konsultasi konsultasi = new Konsultasi();
        konsultasi.setId_konsultasi(txtIdKonsultasi.getText());
        konsultasi.setId_klient(txtIdKlientKonsultasi.getText());
        konsultasi.setPertanyaan(areaPertanyaanKonsultasi.getText());
        konsultasi.setTanggal(dateKonsultasi.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        konsultasi.setStatus(cmbStatusKonsultasi.getSelectedItem().toString());
        
        
        this.servicekonsultasi.tambahKonsultasi(konsultasi);
        Util.resetForm(txtIdKonsultasi, txtIdKlientKonsultasi);
        Util.resetForm(areaPertanyaanKonsultasi);
        Util.resetForm(cmbStatusKonsultasi);
    }//GEN-LAST:event_btnInputKonsultasiActionPerformed

    private void btnCariAdvokatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariAdvokatActionPerformed
      this.serviceadvokat.cariAdvokatById(txtCariAdvokat.getText());
      
      Util.resetForm(txtCariAdvokat);
    }//GEN-LAST:event_btnCariAdvokatActionPerformed

    private void btnCariKlientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKlientActionPerformed
        this.serviceklient.cariKlientById(txtCariKlient.getText());
        
        Util.resetForm(txtCariKlient);
    }//GEN-LAST:event_btnCariKlientActionPerformed

    private void btnCariKonsultasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKonsultasiActionPerformed
        this.servicekonsultasi.cariKonsultasiByID(txtCariKonsultasi.getText());
        
        Util.resetForm(txtCariKonsultasi);
        
    }//GEN-LAST:event_btnCariKonsultasiActionPerformed

    private void btnCariAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariAnalisisActionPerformed
        this.serviceanalisis.cariAnalisisHukumById(txtCariAnalisis.getText());
        
        Util.resetForm(txtCariAnalisis);
    }//GEN-LAST:event_btnCariAnalisisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel Menu;
    private javax.swing.JTextArea areaAnalisis;
    private javax.swing.JTextArea areaPertanyaanKonsultasi;
    private javax.swing.JTextArea areaRekomedasiAnalisis;
    private javax.swing.JButton btnAdvokat;
    private javax.swing.JButton btnAnalisis;
    private javax.swing.JButton btnCariAdvokat;
    private javax.swing.JButton btnCariAnalisis;
    private javax.swing.JButton btnCariKlient;
    private javax.swing.JButton btnCariKonsultasi;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInputAdvokat;
    private javax.swing.JButton btnInputAnalisis;
    private javax.swing.JButton btnInputKlient;
    private javax.swing.JButton btnInputKonsultasi;
    private javax.swing.JButton btnKlient;
    private javax.swing.JButton btnKonsultasi;
    private javax.swing.JComboBox<String> cmbStatusKonsultasi;
    private com.toedter.calendar.JDateChooser dateAnalisis;
    private com.toedter.calendar.JDateChooser dateKonsultasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlAdvokat;
    private javax.swing.JPanel pnlAnalisis;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKlient;
    private javax.swing.JPanel pnlKonsultasi;
    private javax.swing.JPasswordField pwAdvokat;
    private javax.swing.JPasswordField pwKlient;
    private javax.swing.JTextField txtCariAdvokat;
    private javax.swing.JTextField txtCariAnalisis;
    private javax.swing.JTextField txtCariKlient;
    private javax.swing.JTextField txtCariKonsultasi;
    private javax.swing.JTextField txtEmailAdvokat;
    private javax.swing.JTextField txtEmailKlient;
    private javax.swing.JTextField txtIdAdvokat;
    private javax.swing.JTextField txtIdAdvokatAnalisis;
    private javax.swing.JTextField txtIdAnalisis;
    private javax.swing.JTextField txtIdKlient;
    private javax.swing.JTextField txtIdKlientKonsultasi;
    private javax.swing.JTextField txtIdKonsultasi;
    private javax.swing.JTextField txtIdKonsultasiAnalisis;
    private javax.swing.JTextField txtIdentitasAdvokat;
    private javax.swing.JTextField txtIdentitasKlient;
    private javax.swing.JTextField txtNamaAdvokat;
    private javax.swing.JTextField txtNamaKlient;
    private javax.swing.JTextField txtTelpAdvokat;
    private javax.swing.JTextField txtTelpKlient;
    // End of variables declaration//GEN-END:variables

}
